// User Management Service API
//
// A service for managing users, authentication, and authorization.
//
// Schemes: http
// Host: localhost:8081
// BasePath: /api/v1
// Version: 1.0.0
// Contact: Support Github : @aidensV
//
// Consumes:
// - application/json
//
// Produces:
// - application/json
//
// swagger:meta
package main

import (
	"log"
	"time"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"user-management/internal/config"
	"user-management/internal/controllers"
	"user-management/internal/database"
	"user-management/internal/middleware"

	// Import docs (generated by swag)
	_ "user-management/docs"
)

func main() {
	// Load configuration
	if err := config.LoadConfig(); err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// Initialize database
	if err := database.InitDB(); err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}
	defer database.CloseDB()

	// Start background cleanup for expired sessions
	go startSessionCleanup()

	// Setup Gin
	gin.SetMode(config.AppConfig.GinMode)
	router := gin.New()

	// Middleware
	router.Use(middleware.CORS())
	router.Use(middleware.Logger())
	router.Use(middleware.Recovery())

	// Swagger route (bisa diakses tanpa auth)
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Initialize controllers
	authController := controllers.NewAuthController()
	userController := controllers.NewUserController()
	roleController := controllers.NewRoleController()
	permissionController := controllers.NewPermissionController()
	menuController := controllers.NewMenuController()
	loginHistoryController := controllers.NewLoginHistoryController()
	passwordResetController := controllers.NewPasswordResetController()
	authMiddleware := middleware.NewAuthMiddleware()

	// API routes
	api := router.Group("/api/v1")
	{
		// Public routes (no auth required)
		auth := api.Group("/auth")
		{
			auth.POST("/login", authController.Login)
			auth.POST("/forgot-password", passwordResetController.ForgotPassword)
			auth.POST("/reset-password", passwordResetController.ResetPassword)
			auth.POST("/validate-reset-token", passwordResetController.ValidateResetToken)
		}

		// Protected routes (auth required)
		protected := api.Group("/")
		protected.Use(authMiddleware.Authenticate())
		{
			// Auth
			protected.POST("/auth/logout", authController.Logout)
			protected.GET("/auth/me", authController.GetMe)
			protected.GET("/auth/history", loginHistoryController.GetMyLoginHistory)

			// Users (admin only)
			protected.GET("/users", middleware.RequireAdmin(), userController.GetAllUsers)
			protected.GET("/users/:userId", middleware.RequireAdmin(), userController.GetUser)
			protected.POST("/users", middleware.RequireAdmin(), userController.CreateUser)
			protected.PUT("/users/:userId", middleware.RequireAdmin(), userController.UpdateUser)
			protected.DELETE("/users/:userId", middleware.RequireAdmin(), userController.DeleteUser)

			// User Roles (admin only)
			protected.GET("/users/:userId/roles", middleware.RequireAdmin(), roleController.GetUserRoles)
			protected.POST("/users/:userId/roles", middleware.RequireAdmin(), roleController.AssignRoleToUser)
			protected.DELETE("/users/:userId/roles/:roleId", middleware.RequireAdmin(), roleController.RemoveRoleFromUser)

			// Roles (admin only)
			protected.GET("/roles", middleware.RequireAdmin(), roleController.GetAllRoles)
			protected.GET("/roles/:roleId", middleware.RequireAdmin(), roleController.GetRoleByID)
			protected.POST("/roles", middleware.RequireAdmin(), roleController.CreateRole)
			protected.PUT("/roles/:roleId", middleware.RequireAdmin(), roleController.UpdateRole)
			protected.DELETE("/roles/:roleId", middleware.RequireAdmin(), roleController.DeleteRole)

			// Role Menus (admin only)
			protected.GET("/roles/:roleId/menus", middleware.RequireAdmin(), menuController.GetMenusByRole)
			protected.POST("/roles/:roleId/menus/:menuId", middleware.RequireAdmin(), menuController.AssignMenuToRole)
			protected.DELETE("/roles/:roleId/menus/:menuId", middleware.RequireAdmin(), menuController.RemoveMenuFromRole)

			// Permissions (admin only)
			protected.GET("/permissions", middleware.RequireAdmin(), permissionController.GetAllPermissions)
			protected.POST("/permissions", middleware.RequireAdmin(), permissionController.CreatePermission)
			protected.GET("/roles/:roleId/permissions", middleware.RequireAdmin(), permissionController.GetPermissionsByRole)
			protected.POST("/roles/:roleId/permissions/:permissionId", middleware.RequireAdmin(), permissionController.AssignPermissionToRole)
			protected.DELETE("/roles/:roleId/permissions/:permissionId", middleware.RequireAdmin(), permissionController.RemovePermissionFromRole)

			// Menus (admin only)
			protected.GET("/menus", middleware.RequireAdmin(), menuController.GetAllMenus)
			protected.GET("/menus/tree", menuController.GetMenuTree)  // Bisa diakses semua user yang login
			protected.GET("/menus/user", menuController.GetUserMenus) // Menus for current user
			protected.POST("/menus", middleware.RequireAdmin(), menuController.CreateMenu)
			protected.PUT("/menus/:id", middleware.RequireAdmin(), menuController.UpdateMenu)
			protected.DELETE("/menus/:id", middleware.RequireAdmin(), menuController.DeleteMenu)

			// Login History (admin only)
			protected.GET("/login-history", middleware.RequireAdmin(), loginHistoryController.GetAllLoginHistory)
		}
	}

	// Health check
	router.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status":  "ok",
			"service": "user-management",
			"version": "2.0.0",
			"time":    time.Now().Format(time.RFC3339),
		})
	})

	// Start server
	log.Printf("Server starting on port %s", config.AppConfig.Port)
	log.Printf("Swagger UI available at: http://localhost:%s/swagger/index.html", config.AppConfig.Port)
	if err := router.Run(":" + config.AppConfig.Port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}

// startSessionCleanup runs background job to clean expired sessions
func startSessionCleanup() {
	ticker := time.NewTicker(1 * time.Hour)
	defer ticker.Stop()

	for range ticker.C {
		if database.DB != nil {
			result := database.DB.Exec("DELETE FROM user_sessions WHERE expires_at < NOW()")
			if result.Error != nil {
				log.Printf("Failed to clean expired sessions: %v", result.Error)
			} else if result.RowsAffected > 0 {
				log.Printf("Cleaned up %d expired sessions", result.RowsAffected)
			}
		}
	}
}

// startTokenCleanup runs background job to clean expired password reset tokens
func startTokenCleanup() {
	ticker := time.NewTicker(6 * time.Hour)
	defer ticker.Stop()

	for range ticker.C {
		if database.DB != nil {
			result := database.DB.Exec("DELETE FROM password_reset_tokens WHERE expires_at < NOW()")
			if result.Error != nil {
				log.Printf("Failed to clean expired reset tokens: %v", result.Error)
			} else if result.RowsAffected > 0 {
				log.Printf("Cleaned up %d expired reset tokens", result.RowsAffected)
			}

			// Clean old login history (keep last 30 days)
			result = database.DB.Exec("DELETE FROM login_history WHERE created_at < NOW() - INTERVAL '30 days'")
			if result.Error != nil {
				log.Printf("Failed to clean old login history: %v", result.Error)
			} else if result.RowsAffected > 0 {
				log.Printf("Cleaned up %d old login history records", result.RowsAffected)
			}
		}
	}
}
